// Generated by CoffeeScript 1.4.0
(function() {

  this.Subview = (function() {

    function Subview(options) {
      var _this = this;
      $.each(options, function(key, value) {
        return _this[key] = value;
      });
      this.initialize();
      this.render();
      this.bind();
    }

    Subview.prototype.$ = function(selector) {
      return $(selector, this.el);
    };

    Subview.prototype.initialize = function() {};

    Subview.prototype.render = function() {};

    Subview.prototype.bind = function() {};

    return Subview;

  })();

}).call(this);
