// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.PeerGradingProblemBackend = (function() {

    function PeerGradingProblemBackend(ajax_url, mock_backend) {
      this.mock_backend = mock_backend;
      this.ajax_url = ajax_url;
      this.mock_cnt = 0;
    }

    PeerGradingProblemBackend.prototype.post = function(cmd, data, callback) {
      var _this = this;
      if (this.mock_backend) {
        return callback(this.mock(cmd, data));
      } else {
        return $.post(this.ajax_url + cmd, data, callback).error(function() {
          return callback({
            success: false,
            error: "Error occured while performing this operation"
          });
        });
      }
    };

    PeerGradingProblemBackend.prototype.mock = function(cmd, data) {
      var response;
      if (cmd === 'is_student_calibrated') {
        response = {
          success: true,
          calibrated: this.mock_cnt >= 2
        };
      } else if (cmd === 'show_calibration_essay') {
        this.mock_cnt++;
        response = {
          success: true,
          submission_id: 1,
          submission_key: 'abcd',
          student_response: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.\n\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.',
          prompt: '<h2>S11E3: Metal Bands</h2>\n<p>Shown below are schematic band diagrams for two different metals. Both diagrams appear different, yet both of the elements are undisputably metallic in nature.</p>\n<p>* Why is it that both sodium and magnesium behave as metals, even though the s-band of magnesium is filled? </p>\n<p>This is a self-assessed open response question. Please use as much space as you need in the box below to answer the question.</p>',
          rubric: '<table class="rubric"><tbody><tr><th>Purpose</th>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-0" id="score-0-0" value="0"><label for="score-0-0">No product</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-0" id="score-0-1" value="1"><label for="score-0-1">Unclear purpose or main idea</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-0" id="score-0-2" value="2"><label for="score-0-2">Communicates an identifiable purpose and/or main idea for an audience</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-0" id="score-0-3" value="3"><label for="score-0-3">Achieves a clear and distinct purpose for a targeted audience and communicates main ideas with effectively used techniques to introduce and represent ideas and insights</label>\n</td>\n</tr><tr><th>Organization</th>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-1" id="score-1-0" value="0"><label for="score-1-0">No product</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-1" id="score-1-1" value="1"><label for="score-1-1">Organization is unclear; introduction, body, and/or conclusion are underdeveloped, missing or confusing.</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-1" id="score-1-2" value="2"><label for="score-1-2">Organization is occasionally unclear; introduction, body or conclusion may be underdeveloped.</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-1" id="score-1-3" value="3"><label for="score-1-3">Organization is clear and easy to follow; introduction, body and conclusion are defined and aligned with purpose.</label>\n</td>\n</tr></tbody></table>',
          max_score: 4
        };
      } else if (cmd === 'get_next_submission') {
        response = {
          success: true,
          submission_id: 1,
          submission_key: 'abcd',
          student_response: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec tristique ante. Proin at mauris sapien, quis varius leo. Morbi laoreet leo nisi. Morbi aliquam lacus ante. Cras iaculis velit sed diam mattis a fermentum urna luctus. Duis consectetur nunc vitae felis facilisis eget vulputate risus viverra. Cras consectetur ullamcorper lobortis. Nam eu gravida lorem. Nulla facilisi. Nullam quis felis enim. Mauris orci lectus, dictum id cursus in, vulputate in massa.\n\nPhasellus non varius sem. Nullam commodo lacinia odio sit amet egestas. Donec ullamcorper sapien sagittis arcu volutpat placerat. Phasellus ut pretium ante. Nam dictum pulvinar nibh dapibus tristique. Sed at tellus mi, fringilla convallis justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tristique rutrum nulla sed eleifend. Praesent at nunc arcu. Mauris condimentum faucibus nibh, eget commodo quam viverra sed. Morbi in tincidunt dolor. Morbi sed augue et augue interdum fermentum.\n\nCurabitur tristique purus ac arcu consequat cursus. Cras diam felis, dignissim quis placerat at, aliquet ac metus. Mauris vulputate est eu nibh imperdiet varius. Cras aliquet rhoncus elit a laoreet. Mauris consectetur erat et erat scelerisque eu faucibus dolor consequat. Nam adipiscing sagittis nisl, eu mollis massa tempor ac. Nulla scelerisque tempus blandit. Phasellus ac ipsum eros, id posuere arcu. Nullam non sapien arcu. Vivamus sit amet lorem justo, ac tempus turpis. Suspendisse pharetra gravida imperdiet. Pellentesque lacinia mi eu elit luctus pellentesque. Sed accumsan libero a magna elementum varius. Nunc eget pellentesque metus. ',
          prompt: '<h2>S11E3: Metal Bands</h2>\n<p>Shown below are schematic band diagrams for two different metals. Both diagrams appear different, yet both of the elements are undisputably metallic in nature.</p>\n<p>* Why is it that both sodium and magnesium behave as metals, even though the s-band of magnesium is filled? </p>\n<p>This is a self-assessed open response question. Please use as much space as you need in the box below to answer the question.</p>',
          rubric: '<table class="rubric"><tbody><tr><th>Purpose</th>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-0" id="score-0-0" value="0"><label for="score-0-0">No product</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-0" id="score-0-1" value="1"><label for="score-0-1">Unclear purpose or main idea</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-0" id="score-0-2" value="2"><label for="score-0-2">Communicates an identifiable purpose and/or main idea for an audience</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-0" id="score-0-3" value="3"><label for="score-0-3">Achieves a clear and distinct purpose for a targeted audience and communicates main ideas with effectively used techniques to introduce and represent ideas and insights</label>\n</td>\n</tr><tr><th>Organization</th>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-1" id="score-1-0" value="0"><label for="score-1-0">No product</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-1" id="score-1-1" value="1"><label for="score-1-1">Organization is unclear; introduction, body, and/or conclusion are underdeveloped, missing or confusing.</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-1" id="score-1-2" value="2"><label for="score-1-2">Organization is occasionally unclear; introduction, body or conclusion may be underdeveloped.</label>\n</td>\n\n<td>\n<input type="radio" class="score-selection" name="score-selection-1" id="score-1-3" value="3"><label for="score-1-3">Organization is clear and easy to follow; introduction, body and conclusion are defined and aligned with purpose.</label>\n</td>\n</tr></tbody></table>',
          max_score: 4
        };
      } else if (cmd === 'save_calibration_essay') {
        response = {
          success: true,
          actual_score: 2
        };
      } else if (cmd === 'save_grade') {
        response = {
          success: true
        };
      }
      return response;
    };

    return PeerGradingProblemBackend;

  })();

  this.PeerGradingProblem = (function() {

    function PeerGradingProblem(backend) {
      this.collapse_question = __bind(this.collapse_question, this);

      this.gentle_alert = __bind(this.gentle_alert, this);

      this.setup_score_selection = __bind(this.setup_score_selection, this);

      this.show_submit_button = __bind(this.show_submit_button, this);

      this.render_error = __bind(this.render_error, this);

      this.render_calibration_interstitial_page = __bind(this.render_calibration_interstitial_page, this);

      this.render_interstitial_page = __bind(this.render_interstitial_page, this);

      this.render_calibration_feedback = __bind(this.render_calibration_feedback, this);

      this.render_submission_data = __bind(this.render_submission_data, this);

      this.render_submission = __bind(this.render_submission, this);

      this.render_calibration = __bind(this.render_calibration, this);

      this.keydown_handler = __bind(this.keydown_handler, this);

      this.graded_callback = __bind(this.graded_callback, this);

      this.submission_callback = __bind(this.submission_callback, this);

      this.calibration_callback = __bind(this.calibration_callback, this);

      this.calibration_check_callback = __bind(this.calibration_check_callback, this);

      this.submit_grade = __bind(this.submit_grade, this);

      this.submit_calibration_essay = __bind(this.submit_calibration_essay, this);

      this.fetch_submission_essay = __bind(this.fetch_submission_essay, this);

      this.fetch_calibration_essay = __bind(this.fetch_calibration_essay, this);

      this.is_calibrated_check = __bind(this.is_calibrated_check, this);

      var _this = this;
      this.prompt_wrapper = $('.prompt-wrapper');
      this.backend = backend;
      this.location = $('.peer-grading').data('location');
      if (!this.location) {
        return;
      }
      this.submission_container = $('.submission-container');
      this.prompt_container = $('.prompt-container');
      this.rubric_container = $('.rubric-container');
      this.flag_student_container = $('.flag-student-container');
      this.answer_unknown_container = $('.answer-unknown-container');
      this.calibration_panel = $('.calibration-panel');
      this.grading_panel = $('.grading-panel');
      this.content_panel = $('.content-panel');
      this.grading_message = $('.grading-message');
      this.grading_message.hide();
      this.question_header = $('.question-header');
      this.question_header.click(this.collapse_question);
      this.grading_wrapper = $('.grading-wrapper');
      this.calibration_feedback_panel = $('.calibration-feedback');
      this.interstitial_page = $('.interstitial-page');
      this.interstitial_page.hide();
      this.calibration_interstitial_page = $('.calibration-interstitial-page');
      this.calibration_interstitial_page.hide();
      this.error_container = $('.error-container');
      this.submission_key_input = $("input[name='submission-key']");
      this.essay_id_input = $("input[name='essay-id']");
      this.feedback_area = $('.feedback-area');
      this.score_selection_container = $('.score-selection-container');
      this.rubric_selection_container = $('.rubric-selection-container');
      this.grade = null;
      this.calibration = null;
      this.submit_button = $('.submit-button');
      this.action_button = $('.action-button');
      this.calibration_feedback_button = $('.calibration-feedback-button');
      this.interstitial_page_button = $('.interstitial-page-button');
      this.calibration_interstitial_page_button = $('.calibration-interstitial-page-button');
      this.flag_student_checkbox = $('.flag-checkbox');
      this.answer_unknown_checkbox = $('.answer-unknown-checkbox');
      $(window).keydown(this.keydown_handler);
      this.collapse_question();
      Collapsible.setCollapsibles(this.content_panel);
      this.action_button.click(function() {
        return history.back();
      });
      this.calibration_feedback_button.click(function() {
        _this.calibration_feedback_panel.hide();
        _this.grading_wrapper.show();
        _this.gentle_alert("Calibration essay saved.  Fetched the next essay.");
        return _this.is_calibrated_check();
      });
      this.interstitial_page_button.click(function() {
        _this.interstitial_page.hide();
        return _this.is_calibrated_check();
      });
      this.calibration_interstitial_page_button.click(function() {
        _this.calibration_interstitial_page.hide();
        return _this.is_calibrated_check();
      });
      this.calibration_feedback_button.hide();
      this.calibration_feedback_panel.hide();
      this.error_container.hide();
      this.is_calibrated_check();
    }

    PeerGradingProblem.prototype.is_calibrated_check = function() {
      return this.backend.post('is_student_calibrated', {
        location: this.location
      }, this.calibration_check_callback);
    };

    PeerGradingProblem.prototype.fetch_calibration_essay = function() {
      return this.backend.post('show_calibration_essay', {
        location: this.location
      }, this.render_calibration);
    };

    PeerGradingProblem.prototype.fetch_submission_essay = function() {
      return this.backend.post('get_next_submission', {
        location: this.location
      }, this.render_submission);
    };

    PeerGradingProblem.prototype.construct_data = function() {
      var data;
      data = {
        rubric_scores: Rubric.get_score_list(),
        score: Rubric.get_total_score(),
        location: this.location,
        submission_id: this.essay_id_input.val(),
        submission_key: this.submission_key_input.val(),
        feedback: this.feedback_area.val(),
        submission_flagged: this.flag_student_checkbox.is(':checked'),
        answer_unknown: this.answer_unknown_checkbox.is(':checked')
      };
      return data;
    };

    PeerGradingProblem.prototype.submit_calibration_essay = function() {
      var data;
      data = this.construct_data();
      return this.backend.post('save_calibration_essay', data, this.calibration_callback);
    };

    PeerGradingProblem.prototype.submit_grade = function() {
      var data;
      data = this.construct_data();
      return this.backend.post('save_grade', data, this.submission_callback);
    };

    PeerGradingProblem.prototype.calibration_check_callback = function(response) {
      if (response.success) {
        if (response.calibrated && (this.calibration === null || this.calibration === false)) {
          this.calibration = false;
          return this.fetch_submission_essay();
        } else if (response.calibrated && this.calibration === true) {
          this.calibration = false;
          return this.render_interstitial_page();
        } else if (!response.calibrated && this.calibration === null) {
          this.calibration = true;
          return this.render_calibration_interstitial_page();
        } else {
          this.calibration = true;
          return this.fetch_calibration_essay();
        }
      } else if (response.error) {
        return this.render_error(response.error);
      } else {
        return this.render_error("Error contacting the grading service");
      }
    };

    PeerGradingProblem.prototype.calibration_callback = function(response) {
      if (response.success) {
        return this.render_calibration_feedback(response);
      } else if (response.error) {
        return this.render_error(response.error);
      } else {
        return this.render_error("Error saving calibration score");
      }
    };

    PeerGradingProblem.prototype.submission_callback = function(response) {
      if (response.success) {
        this.is_calibrated_check();
        this.grading_message.fadeIn();
        return this.grading_message.html("<p>Successfully saved your feedback. Fetched the next essay.</p>");
      } else {
        if (response.error) {
          return this.render_error(response.error);
        } else {
          return this.render_error("Error occurred while submitting grade");
        }
      }
    };

    PeerGradingProblem.prototype.graded_callback = function(event) {
      if (Rubric.check_complete()) {
        this.grading_message.hide();
        this.show_submit_button();
        return this.grade = Rubric.get_total_score();
      }
    };

    PeerGradingProblem.prototype.keydown_handler = function(event) {
      if (event.which === 13 && this.submit_button.is(':visible')) {
        if (this.calibration) {
          return this.submit_calibration_essay();
        } else {
          return this.submit_grade();
        }
      }
    };

    PeerGradingProblem.prototype.render_calibration = function(response) {
      if (response.success) {
        this.submission_container.html("");
        this.render_submission_data(response);
        this.calibration_panel.addClass('current-state');
        this.grading_panel.removeClass('current-state');
        this.calibration_panel.find('.calibration-text').show();
        this.grading_panel.find('.calibration-text').show();
        this.calibration_panel.find('.grading-text').hide();
        this.grading_panel.find('.grading-text').hide();
        this.flag_student_container.hide();
        this.answer_unknown_container.hide();
        this.feedback_area.val("");
        this.submit_button.unbind('click');
        return this.submit_button.click(this.submit_calibration_essay);
      } else if (response.error) {
        return this.render_error(response.error);
      } else {
        return this.render_error("An error occurred while retrieving the next calibration essay");
      }
    };

    PeerGradingProblem.prototype.render_submission = function(response) {
      if (response.success) {
        this.submit_button.hide();
        this.submission_container.html("");
        this.render_submission_data(response);
        this.calibration_panel.removeClass('current-state');
        this.grading_panel.addClass('current-state');
        this.calibration_panel.find('.calibration-text').hide();
        this.grading_panel.find('.calibration-text').hide();
        this.calibration_panel.find('.grading-text').show();
        this.grading_panel.find('.grading-text').show();
        this.flag_student_container.show();
        this.answer_unknown_container.show();
        this.feedback_area.val("");
        this.submit_button.unbind('click');
        return this.submit_button.click(this.submit_grade);
      } else if (response.error) {
        return this.render_error(response.error);
      } else {
        return this.render_error("An error occured when retrieving the next submission.");
      }
    };

    PeerGradingProblem.prototype.make_paragraphs = function(text) {
      var new_text, paragraph, paragraph_split, _i, _len;
      paragraph_split = text.split(/\n\s*\n/);
      new_text = '';
      for (_i = 0, _len = paragraph_split.length; _i < _len; _i++) {
        paragraph = paragraph_split[_i];
        new_text += "<p>" + paragraph + "</p>";
      }
      return new_text;
    };

    PeerGradingProblem.prototype.render_submission_data = function(response) {
      this.content_panel.show();
      this.error_container.hide();
      this.submission_container.append(this.make_paragraphs(response.student_response));
      this.prompt_container.html(response.prompt);
      this.rubric_selection_container.html(response.rubric);
      this.submission_key_input.val(response.submission_key);
      this.essay_id_input.val(response.submission_id);
      this.setup_score_selection(response.max_score);
      this.submit_button.hide();
      this.action_button.hide();
      this.calibration_feedback_panel.hide();
      return Rubric.initialize(this.location);
    };

    PeerGradingProblem.prototype.render_calibration_feedback = function(response) {
      var actual_score, calibration_wrapper, score;
      this.calibration_feedback_panel.slideDown();
      calibration_wrapper = $('.calibration-feedback-wrapper');
      calibration_wrapper.html("<p>The score you gave was: " + this.grade + ". The actual score is: " + response.actual_score + "</p>");
      score = parseInt(this.grade);
      actual_score = parseInt(response.actual_score);
      if (score === actual_score) {
        calibration_wrapper.append("<p>Your score matches the actual score!</p>");
      } else {
        calibration_wrapper.append("<p>You may want to review the rubric again.</p>");
      }
      $("input[name='score-selection']").attr('disabled', true);
      this.submit_button.hide();
      return this.calibration_feedback_button.show();
    };

    PeerGradingProblem.prototype.render_interstitial_page = function() {
      this.content_panel.hide();
      this.grading_message.hide();
      return this.interstitial_page.show();
    };

    PeerGradingProblem.prototype.render_calibration_interstitial_page = function() {
      this.content_panel.hide();
      this.action_button.hide();
      return this.calibration_interstitial_page.show();
    };

    PeerGradingProblem.prototype.render_error = function(error_message) {
      this.error_container.show();
      this.calibration_feedback_panel.hide();
      this.error_container.html(error_message);
      this.content_panel.hide();
      return this.action_button.show();
    };

    PeerGradingProblem.prototype.show_submit_button = function() {
      return this.submit_button.show();
    };

    PeerGradingProblem.prototype.setup_score_selection = function(max_score) {
      return $("input[class='score-selection']").change(this.graded_callback);
    };

    PeerGradingProblem.prototype.gentle_alert = function(msg) {
      this.grading_message.fadeIn();
      return this.grading_message.html("<p>" + msg + "</p>");
    };

    PeerGradingProblem.prototype.collapse_question = function() {
      var new_text;
      this.prompt_container.slideToggle();
      this.prompt_container.toggleClass('open');
      if (this.question_header.text() === "(Hide)") {
        Logger.log('peer_grading_hide_question', {
          location: this.location
        });
        new_text = "(Show)";
      } else {
        Logger.log('peer_grading_show_question', {
          location: this.location
        });
        new_text = "(Hide)";
      }
      return this.question_header.text(new_text);
    };

    return PeerGradingProblem;

  })();

}).call(this);
