// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Conditional = (function() {

    function Conditional(element) {
      this.updateProgress = __bind(this.updateProgress, this);
      this.el = $(element).find('.conditional-wrapper');
      this.id = this.el.data('problem-id');
      this.element_id = this.el.attr('id');
      this.url = this.el.data('url');
      this.render();
    }

    Conditional.prototype.$ = function(selector) {
      return $(selector, this.el);
    };

    Conditional.prototype.updateProgress = function(response) {
      if (response.progress_changed) {
        this.el.attr({
          progress: response.progress_status
        });
        return this.el.trigger('progressChanged');
      }
    };

    Conditional.prototype.render = function(content) {
      var _this = this;
      if (content) {
        this.el.html(content);
        return XModule.loadModules(this.el);
      } else {
        return $.postWithPrefix("" + this.url + "/conditional_get", function(response) {
          _this.el.html(response.html);
          return XModule.loadModules(_this.el);
        });
      }
    };

    return Conditional;

  })();

}).call(this);
