// Generated by CoffeeScript 1.4.0
(function() {

  this.SubviewAlpha = (function() {

    function SubviewAlpha(options) {
      var _this = this;
      $.each(options, function(key, value) {
        return _this[key] = value;
      });
      this.initialize();
      this.render();
      this.bind();
    }

    SubviewAlpha.prototype.$ = function(selector) {
      return $(selector, this.el);
    };

    SubviewAlpha.prototype.initialize = function() {};

    SubviewAlpha.prototype.render = function() {};

    SubviewAlpha.prototype.bind = function() {};

    return SubviewAlpha;

  })();

}).call(this);
