// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.VideoCaptionAlpha = (function(_super) {

    __extends(VideoCaptionAlpha, _super);

    function VideoCaptionAlpha() {
      this.hideCaptions = __bind(this.hideCaptions, this);

      this.toggle = __bind(this.toggle, this);

      this.seekPlayer = __bind(this.seekPlayer, this);

      this.onMouseLeave = __bind(this.onMouseLeave, this);

      this.onMovement = __bind(this.onMovement, this);

      this.onMouseEnter = __bind(this.onMouseEnter, this);

      this.resize = __bind(this.resize, this);
      return VideoCaptionAlpha.__super__.constructor.apply(this, arguments);
    }

    VideoCaptionAlpha.prototype.initialize = function() {
      return this.loaded = false;
    };

    VideoCaptionAlpha.prototype.bind = function() {
      $(window).bind('resize', this.resize);
      this.$('.hide-subtitles').click(this.toggle);
      return this.$('.subtitles').mouseenter(this.onMouseEnter).mouseleave(this.onMouseLeave).mousemove(this.onMovement).bind('mousewheel', this.onMovement).bind('DOMMouseScroll', this.onMovement);
    };

    VideoCaptionAlpha.prototype.captionURL = function() {
      return "" + this.captionAssetPath + this.youtubeId + ".srt.sjson";
    };

    VideoCaptionAlpha.prototype.render = function() {
      this.$('.video-wrapper').after("<ol class=\"subtitles\"></ol>");
      this.$('.video-controls .secondary-controls').append("<a href=\"#\" class=\"hide-subtitles\" title=\"Turn off captions\">Captions</a>");
      this.$('.subtitles').css({
        maxHeight: this.$('.video-wrapper').height() - 5
      });
      return this.fetchCaption();
    };

    VideoCaptionAlpha.prototype.fetchCaption = function() {
      var _this = this;
      return $.getWithPrefix(this.captionURL(), function(captions) {
        _this.captions = captions.text;
        _this.start = captions.start;
        _this.loaded = true;
        if (onTouchBasedDevice()) {
          return $('.subtitles li').html("Caption will be displayed when you start playing the video.");
        } else {
          return _this.renderCaption();
        }
      });
    };

    VideoCaptionAlpha.prototype.renderCaption = function() {
      var container,
        _this = this;
      container = $('<ol>');
      $.each(this.captions, function(index, text) {
        return container.append($('<li>').html(text).attr({
          'data-index': index,
          'data-start': _this.start[index]
        }));
      });
      this.$('.subtitles').html(container.html());
      this.$('.subtitles li[data-index]').click(this.seekPlayer);
      this.$('.subtitles').prepend($('<li class="spacing">').height(this.topSpacingHeight())).append($('<li class="spacing">').height(this.bottomSpacingHeight()));
      return this.rendered = true;
    };

    VideoCaptionAlpha.prototype.search = function(time) {
      var index, max, min;
      if (this.loaded) {
        min = 0;
        max = this.start.length - 1;
        while (min < max) {
          index = Math.ceil((max + min) / 2);
          if (time < this.start[index]) {
            max = index - 1;
          }
          if (time >= this.start[index]) {
            min = index;
          }
        }
        return min;
      }
    };

    VideoCaptionAlpha.prototype.play = function() {
      if (this.loaded) {
        if (!this.rendered) {
          this.renderCaption();
        }
        return this.playing = true;
      }
    };

    VideoCaptionAlpha.prototype.pause = function() {
      if (this.loaded) {
        return this.playing = false;
      }
    };

    VideoCaptionAlpha.prototype.updatePlayTime = function(time) {
      var newIndex;
      if (this.loaded) {
        time = Math.round(Time.convert(time, this.currentSpeed, '1.0') * 1000 + 250);
        newIndex = this.search(time);
        if (newIndex !== void 0 && this.currentIndex !== newIndex) {
          if (this.currentIndex) {
            this.$(".subtitles li.current").removeClass('current');
          }
          this.$(".subtitles li[data-index='" + newIndex + "']").addClass('current');
          this.currentIndex = newIndex;
          return this.scrollCaption();
        }
      }
    };

    VideoCaptionAlpha.prototype.resize = function() {
      this.$('.subtitles').css({
        maxHeight: this.captionHeight()
      });
      this.$('.subtitles .spacing:first').height(this.topSpacingHeight());
      this.$('.subtitles .spacing:last').height(this.bottomSpacingHeight());
      return this.scrollCaption();
    };

    VideoCaptionAlpha.prototype.onMouseEnter = function() {
      if (this.frozen) {
        clearTimeout(this.frozen);
      }
      return this.frozen = setTimeout(this.onMouseLeave, 10000);
    };

    VideoCaptionAlpha.prototype.onMovement = function() {
      return this.onMouseEnter();
    };

    VideoCaptionAlpha.prototype.onMouseLeave = function() {
      if (this.frozen) {
        clearTimeout(this.frozen);
      }
      this.frozen = null;
      if (this.playing) {
        return this.scrollCaption();
      }
    };

    VideoCaptionAlpha.prototype.scrollCaption = function() {
      if (!this.frozen && this.$('.subtitles .current:first').length) {
        return this.$('.subtitles').scrollTo(this.$('.subtitles .current:first'), {
          offset: -this.calculateOffset(this.$('.subtitles .current:first'))
        });
      }
    };

    VideoCaptionAlpha.prototype.seekPlayer = function(event) {
      var time;
      event.preventDefault();
      time = Math.round(Time.convert($(event.target).data('start'), '1.0', this.currentSpeed) / 1000);
      return $(this).trigger('seek', time);
    };

    VideoCaptionAlpha.prototype.calculateOffset = function(element) {
      return this.captionHeight() / 2 - element.height() / 2;
    };

    VideoCaptionAlpha.prototype.topSpacingHeight = function() {
      return this.calculateOffset(this.$('.subtitles li:not(.spacing):first'));
    };

    VideoCaptionAlpha.prototype.bottomSpacingHeight = function() {
      return this.calculateOffset(this.$('.subtitles li:not(.spacing):last'));
    };

    VideoCaptionAlpha.prototype.toggle = function(event) {
      event.preventDefault();
      if (this.el.hasClass('closed')) {
        return this.hideCaptions(false);
      } else {
        return this.hideCaptions(true);
      }
    };

    VideoCaptionAlpha.prototype.hideCaptions = function(hide_captions) {
      if (hide_captions) {
        this.$('.hide-subtitles').attr('title', 'Turn on captions');
        this.el.addClass('closed');
      } else {
        this.$('.hide-subtitles').attr('title', 'Turn off captions');
        this.el.removeClass('closed');
        this.scrollCaption();
      }
      return $.cookie('hide_captions', hide_captions, {
        expires: 3650,
        path: '/'
      });
    };

    VideoCaptionAlpha.prototype.captionHeight = function() {
      if (this.el.hasClass('fullscreen')) {
        return $(window).height() - this.$('.video-controls').height();
      } else {
        return this.$('.video-wrapper').height();
      }
    };

    return VideoCaptionAlpha;

  })(SubviewAlpha);

}).call(this);
