// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.VerticalDescriptor = (function(_super) {

    __extends(VerticalDescriptor, _super);

    function VerticalDescriptor(element) {
      var _this = this;
      this.element = element;
      this.$items = $(this.element).find(".vert-mod");
      this.$items.sortable({
        update: function(event, ui) {
          return _this.update();
        }
      });
    }

    VerticalDescriptor.prototype.save = function() {
      return {
        children: $('.vert-mod li', this.element).map(function(idx, el) {
          return $(el).data('id');
        }).toArray()
      };
    };

    return VerticalDescriptor;

  })(XModule.Descriptor);

}).call(this);
