// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Sequence = (function() {

    function Sequence(element) {
      this.previous = __bind(this.previous, this);

      this.next = __bind(this.next, this);

      this.goto = __bind(this.goto, this);

      this.toggleArrows = __bind(this.toggleArrows, this);

      this.updateProgress = __bind(this.updateProgress, this);
      this.el = $(element).find('.sequence');
      this.contents = this.$('.seq_contents');
      this.num_contents = this.contents.length;
      this.id = this.el.data('id');
      this.modx_url = this.el.data('course_modx_root');
      this.initProgress();
      this.bind();
      this.render(parseInt(this.el.data('position')));
    }

    Sequence.prototype.$ = function(selector) {
      return $(selector, this.el);
    };

    Sequence.prototype.bind = function() {
      return this.$('#sequence-list a').click(this.goto);
    };

    Sequence.prototype.initProgress = function() {
      return this.progressTable = {};
    };

    Sequence.prototype.hookUpProgressEvent = function() {
      return $('.problems-wrapper').bind('progressChanged', this.updateProgress);
    };

    Sequence.prototype.mergeProgress = function(p1, p2) {
      var w1, w2;
      if (p1 === "NA") {
        return p2;
      }
      if (p2 === "NA") {
        return p1;
      }
      if (p1 === "done" && p2 === "done") {
        return "done";
      }
      w1 = p1 === "done" || p1 === "in_progress";
      w2 = p2 === "done" || p2 === "in_progress";
      if (w1 || w2) {
        return "in_progress";
      }
      return "none";
    };

    Sequence.prototype.updateProgress = function() {
      var new_progress, _this;
      new_progress = "NA";
      _this = this;
      $('.problems-wrapper').each(function(index) {
        var progress;
        progress = $(this).attr('progress');
        return new_progress = _this.mergeProgress(progress, new_progress);
      });
      this.progressTable[this.position] = new_progress;
      return this.setProgress(new_progress, this.link_for(this.position));
    };

    Sequence.prototype.setProgress = function(progress, element) {
      element.removeClass('progress-none').removeClass('progress-some').removeClass('progress-done');
      switch (progress) {
        case 'none':
          return element.addClass('progress-none');
        case 'in_progress':
          return element.addClass('progress-some');
        case 'done':
          return element.addClass('progress-done');
      }
    };

    Sequence.prototype.toggleArrows = function() {
      this.$('.sequence-nav-buttons a').unbind('click');
      if (this.position === 1) {
        this.$('.sequence-nav-buttons .prev a').addClass('disabled');
      } else {
        this.$('.sequence-nav-buttons .prev a').removeClass('disabled').click(this.previous);
      }
      if (this.position === this.contents.length) {
        return this.$('.sequence-nav-buttons .next a').addClass('disabled');
      } else {
        return this.$('.sequence-nav-buttons .next a').removeClass('disabled').click(this.next);
      }
    };

    Sequence.prototype.render = function(new_position) {
      var modx_full_url, sequence_links;
      if (this.position !== new_position) {
        if (this.position !== void 0) {
          this.mark_visited(this.position);
          modx_full_url = this.modx_url + '/' + this.id + '/goto_position';
          $.postWithPrefix(modx_full_url, {
            position: new_position
          });
        }
        this.mark_active(new_position);
        this.$('#seq_content').html(this.contents.eq(new_position - 1).text());
        XModule.loadModules(this.$('#seq_content'));
        MathJax.Hub.Queue(["Typeset", MathJax.Hub, "seq_content"]);
        window.update_schematics();
        this.position = new_position;
        this.toggleArrows();
        this.hookUpProgressEvent();
        sequence_links = this.$('#seq_content a.seqnav');
        return sequence_links.click(this.goto);
      }
    };

    Sequence.prototype.goto = function(event) {
      var new_position;
      event.preventDefault();
      if ($(event.target).hasClass('seqnav')) {
        new_position = $(event.target).attr('href');
      } else {
        new_position = $(event.target).data('element');
      }
      if ((1 <= new_position) && (new_position <= this.num_contents)) {
        Logger.log("seq_goto", {
          old: this.position,
          "new": new_position,
          id: this.id
        });
        if (window.queuePollerID) {
          window.clearTimeout(window.queuePollerID);
          delete window.queuePollerID;
        }
        return this.render(new_position);
      } else {
        return alert('Sequence error! Cannot navigate to tab ' + new_position + 'in the current SequenceModule. Please contact the course staff.');
      }
    };

    Sequence.prototype.next = function(event) {
      var new_position;
      event.preventDefault();
      new_position = this.position + 1;
      Logger.log("seq_next", {
        old: this.position,
        "new": new_position,
        id: this.id
      });
      return this.render(new_position);
    };

    Sequence.prototype.previous = function(event) {
      var new_position;
      event.preventDefault();
      new_position = this.position - 1;
      Logger.log("seq_prev", {
        old: this.position,
        "new": new_position,
        id: this.id
      });
      return this.render(new_position);
    };

    Sequence.prototype.link_for = function(position) {
      return this.$("#sequence-list a[data-element=" + position + "]");
    };

    Sequence.prototype.mark_visited = function(position) {
      var element;
      element = this.link_for(position);
      return element.removeClass("inactive").removeClass("active").addClass("visited");
    };

    Sequence.prototype.mark_active = function(position) {
      var element;
      element = this.link_for(position);
      return element.removeClass("inactive").removeClass("visited").addClass("active");
    };

    return Sequence;

  })();

}).call(this);
