// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.SequenceDescriptor = (function(_super) {

    __extends(SequenceDescriptor, _super);

    function SequenceDescriptor(element) {
      var _this = this;
      this.element = element;
      this.$tabs = $(this.element).find("#sequence-list");
      this.$tabs.sortable({
        update: function(event, ui) {
          return _this.update();
        }
      });
    }

    SequenceDescriptor.prototype.save = function() {
      return {
        children: $('#sequence-list li a', this.element).map(function(idx, el) {
          return $(el).data('id');
        }).toArray()
      };
    };

    return SequenceDescriptor;

  })(XModule.Descriptor);

}).call(this);
