// Generated by CoffeeScript 1.4.0
(function() {

  this.Collapsible = (function() {

    function Collapsible() {}

    Collapsible.setCollapsibles = function(el) {
      /*
          el: container
      */

      var short_custom;
      el.find('.longform').hide();
      el.find('.shortform').append('<a href="#" class="full">See full output</a>');
      short_custom = el.find('.shortform-custom');
      short_custom.each(function(index, elt) {
        var close_text, open_text;
        open_text = $(elt).data('open-text');
        close_text = $(elt).data('close-text');
        $(elt).append("<a href='#' class='full-custom'>" + open_text + "</a>");
        return $(elt).find('.full-custom').click(function(event) {
          return Collapsible.toggleFull(event, open_text, close_text);
        });
      });
      el.find('.collapsible header + section').hide();
      el.find('.full').click(function(event) {
        return Collapsible.toggleFull(event, "See full output", "Hide output");
      });
      return el.find('.collapsible header a').click(Collapsible.toggleHint);
    };

    Collapsible.toggleFull = function(event, open_text, close_text) {
      var new_text;
      event.preventDefault();
      $(event.target).parent().siblings().slideToggle();
      $(event.target).parent().parent().toggleClass('open');
      if ($(event.target).text() === open_text) {
        new_text = close_text;
      } else {
        new_text = open_text;
      }
      return $(event.target).text(new_text);
    };

    Collapsible.toggleHint = function(event) {
      event.preventDefault();
      $(event.target).parent().siblings().slideToggle();
      return $(event.target).parent().parent().toggleClass('open');
    };

    return Collapsible;

  }).call(this);

}).call(this);
